//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeService
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeProfile
    {
        public int EmpNo { get; set; }
        public string Name { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
        public string Gender { get; set; }
        public string Position { get; set; }
        public System.DateTime DOB { get; set; }
        public decimal Salary { get; set; }
    }
}
